apiVersion: apps/v1
kind: Deployment
metadata:
  name: petwas
  namespace: pet
  annotations:
    argocd-image-updater.argoproj.io/image-list: petwas=534334097321.dkr.ecr.ap-northeast-2.amazonaws.com/pet/waserver
    argocd-image-updater.argoproj.io/petwas.update-strategy: latest
    app.kubernetes.io/version: "v1"
    changed.by: "dote10"
    change.reason: "frist create"
    change.date: "2025-07-20"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: was
      name: petclinic
  template:
    metadata:
      labels:
        app: was
        name: petclinic
    spec:
      containers:
        - name: petwas
          image: 534334097321.dkr.ecr.ap-northeast-2.amazonaws.com/pet/waserver:20250722035724
          imagePullPolicy: Always  
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: k8s-db-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: k8s-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-db-secret
                  key: DB_PASSWORD