apiVersion: v1
kind: Service
metadata:
  name: pet-was-service
  namespace: pet 
spec:
  selector:
    app: was
    name: petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP